[package]
name = "ores-otel-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI for ores-otel"
repository = "https://github.com/ores-otel/ores-otel-cli"

[[bin]]
name = "ores-otel"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
flags2env = { git = "https://github.com/ORESoftware/flags-2-env.git", rev = "377bff1a4e7424eb98377997a232ddc0fc700f59" }
oresoftware-next-loggers = { git = "https://github.com/ores-otel/ores.otel.log.git", rev = "a5ec8812df692ccc3bdcaaf89d984c44714970d5" }
ores-clis-core = { git = "https://github.com/ORESoftware/ores-clis-core.git", rev = "2ea696bd8dd066483d29c37af9e34036cbae82f9" }

[lints.rust]
unsafe_code = "forbid"
